### ISSUE TITLE
reassign false positives on shadowed names

### ISSUE THREAD

**Issue by MichaelUrman** [curioswitch/go-reassign#5]
Reassign issues false positives for shadowed package names. For example,

```console 
$ go run github.com/curioswitch/go-reassign/cmd@v0.1.2 ./...
/home/murman/src/reassign-broke/foo.go:9:5: reassigning variable EOF in other package fmt
exit status 3
```

This is an otherwise empty directory with a new module (go mod init foo) and a `foo.go` with the following:

```go
package main

import "fmt"

func main() {
    fmt.Println("hi")

    fmt := struct{ EOF int }{}
    fmt.EOF = 5
}
```

I did encounter this in real code while using golangci-lint, albeit shadowing my own packages instead of standard ones, and with a pattern of `.*` instead of the default.

See golangci/golangci-lint#3145 for additional details about the environment in which I ran it, but I don't expect they are necessary.

**Comment by chokoswitch** [comment]
Hi @MichaelUrman - thanks for trying out the linter! Indeed this is a current limitation, but I think it can be fixed will look into it. Just for context, does the lint warning actually help you find and clean up the shadowing itself or you do want to keep the shadowing?

**Comment by MichaelUrman** [comment]
A fair question. I see little benefit to avoiding this shadowing; the differences between the package and local leave little chance of successful misuse. Removing this shadowing would require coming up with either a more cumbersome package name or a less fitting local name than `user`; I suppose `u` for the local may be idiomatic.

If I want to avoid the shadowing more generally, I would probably turn to govet or revive's shadowing checks; reassign only identifies a very specific case.

FWIW, my first thought towards fixing this would be to see if `pass.TypesInfo.Uses[selector.Sel]`, `pass.TypesInfo.Uses[selectIdent]`, or `pass.TypesInfo.Selections[selector]` differentiates locals from imports.

**Comment by chokoswitch** [comment]
@MichaelUrman Thanks for the help, a PR would be wonderful!
